services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=mta_gtfs
      - MTA_API_URL=https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs
    restart: always

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=mta_gtfs
    volumes:
      - ./data:/app/data
    restart: always